name: Deploy Frontend
on:
  push:
    branches:
      - master
     
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Login to DockerHub
          run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        - name: Build Docker image
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-react -f Dockerfile.dev .
        - name: Run Tests
          run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/docker-react npm test

        - name: Generate deployment package
          run: zip -r deploy.zip . -x '*.git*'

        - name: Deploy to EB
          uses: einaregilsson/beanstalk-deploy@v18
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
            application_name: docker-react
            environment_name: Dockerreact-env
            existing_bucket_name: elasticbeanstalk-ap-south-1-652893551902
            region: ap-south-1
            version_label: ${{ github.sha }}
            deployment_package: deploy.zip
